

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projek;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.JOptionPane;
/**
 *
 * @author dafiq
 */
public class aplikasi_hitung_nilai extends javax.swing.JFrame {

    /**
     * Creates new form aplikasi_hitung_nilai
     */
    public aplikasi_hitung_nilai() {
        initComponents();

        tampil_data();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        N_nrp = new javax.swing.JTextField();
        N_nama = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        N_absen = new javax.swing.JTextField();
        N_tugas = new javax.swing.JTextField();
        N_uts = new javax.swing.JTextField();
        N_uas = new javax.swing.JTextField();
        B_submit = new javax.swing.JButton();
        B_clear = new javax.swing.JButton();
        B_exit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        N_akhir = new javax.swing.JTextField();
        N_ket = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        B_Add = new javax.swing.JButton();
        B_edit = new javax.swing.JButton();
        B_hapus = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        N_cari = new javax.swing.JTextField();
        B_cari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("Program Aplikasi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setText("Perhitungan Nilai Mahasiswa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("NRP");

        jLabel4.setText("Nama Mahasiswa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(N_nrp, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(N_nama))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(N_nrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(N_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 500, 100));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Nilai Absen");

        jLabel6.setText("Nilai Tugas");

        jLabel7.setText("Nilai UTS");

        jLabel8.setText("Nilai UAS");

        N_absen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N_absenActionPerformed(evt);
            }
        });

        N_tugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N_tugasActionPerformed(evt);
            }
        });

        N_uas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N_uasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(N_absen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N_tugas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(N_uts, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(N_uas, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(N_absen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(N_tugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(N_uts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(N_uas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 500, 170));

        B_submit.setText("Submit");
        B_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_submitActionPerformed(evt);
            }
        });
        getContentPane().add(B_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        B_clear.setText("Clear");
        B_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_clearActionPerformed(evt);
            }
        });
        getContentPane().add(B_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        B_exit.setText("Exit");
        B_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_exitActionPerformed(evt);
            }
        });
        getContentPane().add(B_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Nilai Akhir");

        jLabel10.setText("Keterangan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                        .addComponent(N_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addComponent(N_ket, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(N_akhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(N_ket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 500, 90));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 560, 350));

        B_Add.setText("Add");
        B_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AddActionPerformed(evt);
            }
        });
        getContentPane().add(B_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        B_edit.setText("Edit");
        B_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_editActionPerformed(evt);
            }
        });
        getContentPane().add(B_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));

        B_hapus.setText("Hapus");
        B_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(B_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, -1, -1));

        jLabel11.setText("Cari");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, -1, -1));
        getContentPane().add(N_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 270, -1));

        B_cari.setText("Cari");
        B_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cariActionPerformed(evt);
            }
        });
        getContentPane().add(B_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void N_absenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N_absenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N_absenActionPerformed

    private void N_uasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N_uasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N_uasActionPerformed

    private void B_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_submitActionPerformed
        double absen, tugas, uts, uas, akhir;
        String hasil;
        
        absen=Double.parseDouble(N_absen.getText());
        tugas=Double.parseDouble(N_tugas.getText());
        uts=Double.parseDouble(N_uts.getText());
        uas=Double.parseDouble(N_uas.getText());
        akhir=(0.2*absen) + (0.25*tugas) + (0.25*uts) + (0.3*uas);
        
        hasil=String.valueOf(akhir);
        N_akhir.setText(hasil);
        
        if(akhir >= 90) {
            N_ket.setText("Selamat anda lulus dengan grade A");
        }
        else if((akhir >=80)&&(akhir<=89)){
            N_ket.setText("selamat anda lulus dengan grade B");
        }
        else if((akhir >=70)&&(akhir<=79)){
            N_ket.setText("selamat anda lulus dengan grade C");
        }
        else if((akhir >=40)&&(akhir<=69)){
            N_ket.setText("maaf anda tidak lulus dengan grade D");
        }
        else if((akhir >=1)&&(akhir<=39)){
            N_ket.setText("maaf anda tidak lulus dengan grade E");
        }
        
        
        
    }//GEN-LAST:event_B_submitActionPerformed

    private void N_tugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N_tugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_N_tugasActionPerformed

    private void B_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_clearActionPerformed
        N_nrp.setText("");
        N_nama.setText("");
        N_absen.setText("");
        N_tugas.setText("");
        N_uts.setText("");
        N_uas.setText("");
        N_akhir.setText("");
        N_ket.setText("");
    }//GEN-LAST:event_B_clearActionPerformed

    private void B_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_exitActionPerformed
        dispose();
    }//GEN-LAST:event_B_exitActionPerformed

    private void B_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AddActionPerformed
       try{
           String sql= "insert into tb_data values('"
                   +N_nrp.getText()+"','"
                   +N_nama.getText()+"','"
                   +N_absen.getText()+"','"
                   +N_tugas.getText()+"','"
                   +N_uts.getText()+"','"
                   +N_uas.getText()+"','"
                   +N_akhir.getText()+"','"
                   +N_ket.getText()+"')";
           java.sql.Connection conn = (java.sql.Connection)projek.Koneksi.connDB();
           java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                   pst.execute();
                   JOptionPane.showMessageDialog(null, "berhasi di simpan");
                   tampil_data();
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, "gagal di simpan");
           System.out.println(e.getMessage());
       }
    }//GEN-LAST:event_B_AddActionPerformed

    private void B_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cariActionPerformed
try {
    java.sql.Connection conn=(java.sql.Connection)projek.Koneksi.connDB();
    String sql = "Select * from tb_data where nrp='"+N_cari.getText()+"' or nama='"+N_cari.getText()+"'";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    ResultSet rs = pst.executeQuery();
    if (rs.next()){
        N_nrp.setText(rs.getString(1));
        N_nama.setText(rs.getString(2));
        N_absen.setText(Double.toString(rs.getDouble(3)));
        N_tugas.setText(Double.toString(rs.getDouble(4)));
        N_uts.setText(Double.toString(rs.getDouble(5)));
        N_uas.setText(Double.toString(rs.getDouble(6)));
        N_akhir.setText(Double.toString(rs.getDouble(7)));
        N_ket.setText(rs.getString(8));
        JOptionPane.showMessageDialog(null,"Data tb_data : "
        + N_cari.getText() + " ditemukan, Apakah Anda Ingin Mengedit atau Menghapus?");
    }
} catch (Exception e){}
N_cari.requestFocus();

    }//GEN-LAST:event_B_cariActionPerformed

    private void B_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_editActionPerformed
 try{
            String sql = "update tb_data set nama='" 
                    + N_nama.getText() + "', nilai_absen='" 
                    + N_absen.getText() + "', nilai_tugas='" 
                    + N_tugas.getText() + "', nilai_uts='" 
                    + N_uts.getText() + "', nilai_uas='" 
                    + N_uas.getText() + "', nilai_akhir='" 
                    + N_akhir.getText() + "', keterangan='" 
                    + N_ket.getText() + "' where nrp='" 
                    + N_nrp.getText() + "'";
                 java.sql.Connection conn=(java.sql.Connection)projek.Koneksi.connDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
            tampil_data();
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal disimpan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_B_editActionPerformed

    private void B_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_hapusActionPerformed
        try{
    java.sql.Connection conn=(java.sql.Connection)projek.Koneksi.connDB();
    String sql = "delete from tb_data where nrp='"+N_nrp.getText()+"' ";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.executeUpdate(); JOptionPane.showMessageDialog(null,"Data berhasil di hapus");
    tampil_data();
    }
catch (Exception e){
JOptionPane.showMessageDialog(null,"Proses Penghapusan Gagal");
System.out.println(e.getMessage());
}
    }//GEN-LAST:event_B_hapusActionPerformed

    public void tampil_data(){
        DefaultTableModel tabel = new DefaultTableModel();
tabel.addColumn("NRP");
tabel.addColumn("NAMA");
tabel.addColumn("N_ABSEN");
tabel.addColumn("N_TUGAS");
tabel.addColumn("N_UTS");
tabel.addColumn("N_UAS");
tabel.addColumn("N_AKHIR");
tabel.addColumn("KET");

try {
    java.sql.Connection conn = (java.sql.Connection) projek.Koneksi.connDB();
        String sql = "SELECT * FROM tb_data ORDER BY `nilai_akhir` DESC";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        
        int rank = 1;
    while (rs.next()) {
        tabel.addRow(new Object[] {
            rank++,
            rs.getString(1),
            rs.getString(2),
            rs.getDouble(3),
            rs.getDouble(4),
            rs.getDouble(5),
            rs.getDouble(6),
            rs.getDouble(7),
            rs.getString(8)
        });
    }

    jTable1.setModel(tabel);
    jTable1.enable(false);
} catch (Exception e) {
    e.printStackTrace(); // Tambahkan ini agar Anda dapat melihat kesalahan jika terjadi
}

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aplikasi_hitung_nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aplikasi_hitung_nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aplikasi_hitung_nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aplikasi_hitung_nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aplikasi_hitung_nilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Add;
    private javax.swing.JButton B_cari;
    private javax.swing.JButton B_clear;
    private javax.swing.JButton B_edit;
    private javax.swing.JButton B_exit;
    private javax.swing.JButton B_hapus;
    private javax.swing.JButton B_submit;
    private javax.swing.JTextField N_absen;
    private javax.swing.JTextField N_akhir;
    private javax.swing.JTextField N_cari;
    private javax.swing.JTextField N_ket;
    private javax.swing.JTextField N_nama;
    private javax.swing.JTextField N_nrp;
    private javax.swing.JTextField N_tugas;
    private javax.swing.JTextField N_uas;
    private javax.swing.JTextField N_uts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
